# https://taskfile.dev

version: "3"

tasks:
  update-deps:
    dir: deps/raylib
    cmds:
      - zig fetch --save=raylib https://github.com/raysan5/raylib/archive/{{.LATEST_RAYLIB}}.tar.gz
      - zig fetch --save=raygui https://github.com/raysan5/raygui/archive/{{.LATEST_RAYGUI}}.tar.gz
    vars:
      LATEST_RAYLIB:
        sh: curl --silent https://api.github.com/repos/raysan5/raylib/commits | jq -r .[0].sha
      LATEST_RAYGUI:
        sh: curl --silent https://api.github.com/repos/raysan5/raygui/commits | jq -r .[0].sha
    silent: true

  web-build:
    cmd: zig build web -Dtarget=wasm32-emscripten --sysroot "$EMSDK/upstream/emscripten" --verbose --release=fast
