name: Zig Build and Release
on:
  release:
    types: [published]

jobs:
  # TODO: multiple architectures
  build-release-macos:
    runs-on: macos-14
    env:
      RELEASE_NAME: zigscene-macos
    permissions:
      contents: write

    name: Build and Release OSX
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zig Setup
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: |
          zig build --release=safe
          mv zig-out/bin/zigscene zig-out/bin/${{env.RELEASE_NAME}}

      - name: Upload for Release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/bin/${{env.RELEASE_NAME}}

  build-release-linux:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: zigscene-linux
    permissions:
      contents: write

    name: Build and Release Linux
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Zig Setup
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: |
          zig build --release=safe
          mv zig-out/bin/zigscene zig-out/bin/${{env.RELEASE_NAME}}

      - name: Upload for Release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/bin/${{env.RELEASE_NAME}}
